[project]
name = "configura"
version = "0.1.0"
description = "Config-driven pipeline engine"
authors = [{ name = "R3MISZ" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
